server:
  port: 7001
  servlet:
    context-path: /medicalassistants/rest
spring:
  application:
    name: medicalassistants-service-rest
  profiles:
    active: sit

mybatis-plus:
  global-config:
    db-config:
      #全局逻辑删除
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #雪花ID
      #主键类型  0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID, 4:全局唯一（UUID）, 5:全局唯一（idWorker的字符串表示）
      #id-type: 3
      #机器 ID 部分(影响雪花ID),不同机器需不同
      #workerId: 1
      #数据标识 ID 部分(影响雪花ID)(workerId 和 datacenterId 一起配置才能重新初始化 Sequence)
      #datacenterId: 1
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      table-underline: true
      db-type: mysql

